version: '3.4'

services:
  gestaodelaboratorios:
    image: ${DOCKER_REGISTRY-}gestaodelaboratorios
    depends_on: 
     - sqlservedb
    build:
      context: .
      dockerfile: GestaoDeLaboratorios/Dockerfile
  
  sqlservedb:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sqlservedb
    ports: # not actually needed, because the two services are on the same network
        - "1433:1433" 
    environment:
        - ACCEPT_EULA=y
        - SA_PASSWORD=yourStrong(!)Password
